const TeamMember = [
  {
    imagePath: "/assest/Manish.jpeg",
    name: "Manish Rawat",
    title: <span style={{ color: "white" }}>Frontend-Developer</span>,
    description: "Passionate about building amazing UIs.",
    twitter: "https://twitter.com/alice",
    github: "https://github.com/manishiiitl1261",
    linkedin: "https://www.linkedin.com/in/manish-rawat-b11960258",
    animation: "left",
  },
  {
    imagePath: "/assest/Manjeet1.jpeg",
    name: "Manjeet Kumar",
    title: <span style={{ color: "white" }}>Backend-Developer</span>,
    description: "Loves scalable and efficient APIs.",
    twitter: "https://twitter.com/bob",
    github: "https://github.com/manjeetkumar29",
    linkedin: "https://www.linkedin.com/in/manjeet-kumar-10a78b259/",
    animation: "right",
  },
  {
    imagePath: "/assest/Astitva1.jpeg",
    name: "Astitva Rajesh",
    title: <span style={{ color: "white" }}>UI/UX-Designer</span>,
    description: "Designs intuitive and modern interfaces.",
    twitter: "https://twitter.com/charlie",
    github: "https://github.com/charlie",
    linkedin: "https://www.linkedin.com/in/astitva-srivastava-0a63a7258/",
    animation: "top",
  },
  {
    imagePath: "/assest/Manjeet1.jpeg",
    name: "Manjeet Kumar",
    title: <span style={{ color: "white" }}>Backend-Developer</span>,
    description: "Loves scalable and efficient APIs.",
    twitter: "https://twitter.com/bob",
    github: "https://github.com/manjeetkumar29",
    linkedin: "https://www.linkedin.com/in/manjeet-kumar-10a78b259/",
    animation: "left",
  },
  {
    imagePath: "/assest/Nimesh11.jpeg",
    name: "Nimesh Dutt",
    title: "Backend Developer",
    description: "Designs intuitive and modern interfaces.",
    twitter: "https://twitter.com/charlie",
    github: "https://github.com/Nimeshdutt?tab=repositories",
    linkedin: "https://www.linkedin.com/in/nimesh-dutt-26948b216/",
    animation: "top",
  },
  {
    imagePath: "/assest/Manish.jpeg",
    name: "Manish Rawat",
    title: <span style={{ color: "white" }}>Frontend-Developer</span>,
    description: "Passionate about building amazing UIs.",
    twitter: "https://twitter.com/alice",
    github: "https://github.com/manishiiitl1261",
    linkedin: "https://www.linkedin.com/in/manish-rawat-b11960258",
    animation: "right",
  },
];

export default TeamMember;
