const TeamMember = [
  {
    imagePath: "/assest/front_img.jpg",
    name: "Alice Johnson",
    title: "Frontend Developer",
    description: "Passionate about building amazing UIs.",
    twitter: "https://twitter.com/alice",
    github: "https://github.com/alice",
    linkedin: "https://linkedin.com/in/alice",
    animation: "left",
  },
  {
    imagePath: "/assest/front_img.jpg",
    name: "Bob Smith",
    title: "Backend Developer",
    description: "Loves scalable and efficient APIs.",
    twitter: "https://twitter.com/bob",
    github: "https://github.com/bob",
    linkedin: "https://linkedin.com/in/bob",
    animation: "right",
  },
  {
    imagePath: "/assest/front_img.jpg",
    name: "Charlie Doe",
    title: "UI/UX Designer",
    description: "Designs intuitive and modern interfaces.",
    twitter: "https://twitter.com/charlie",
    github: "https://github.com/charlie",
    linkedin: "https://linkedin.com/in/charlie",
    animation: "top",
  },
  {
    imagePath: "/assest/front_img.jpg",
    name: "Bob Smith",
    title: "Backend Developer",
    description: "Loves scalable and efficient APIs.",
    twitter: "https://twitter.com/bob",
    github: "https://github.com/bob",
    linkedin: "https://linkedin.com/in/bob",
    animation: "left",
  },
  {
    imagePath: "/assest/front_img.jpg",
    name: "Charlie Doe",
    title: "UI/UX Designer",
    description: "Designs intuitive and modern interfaces.",
    twitter: "https://twitter.com/charlie",
    github: "https://github.com/charlie",
    linkedin: "https://linkedin.com/in/charlie",
    animation: "right",
  },
  {
    imagePath: "/assest/front_img.jpg",
    name: "Charlie Doe",
    title: "UI/UX Designer",
    description: "Designs intuitive and modern interfaces.",
    twitter: "https://twitter.com/charlie",
    github: "https://github.com/charlie",
    linkedin: "https://linkedin.com/in/charlie",
    animation: "right",
  },
];

export default TeamMember;
